workflows:
  # iOS Production Build
  ios-production:
    name: iOS Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.looksmaxxer.app
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  # Android Production Build
  android-production:
    name: Android Production
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - looksmaxxer_keystore
      groups:
        - google_play
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  # Development Build (Both Platforms)
  development:
    name: Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'feature/*'
          include: true
          source: true
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Run tests
        script: |
          flutter test
      - name: Build debug APK
        script: |
          flutter build apk --debug
      - name: Build debug iOS (simulator)
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphonesimulator/*.app
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: false
          failure: true

  # Pull Request Validation
  pull-request:
    name: PR Validation
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: false
        - pattern: 'develop'
          include: true
          source: false
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Check formatting
        script: |
          dart format --output=none --set-exit-if-changed .
      - name: Flutter analyze
        script: |
          flutter analyze --fatal-infos
      - name: Run tests
        script: |
          flutter test --coverage
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: false
          failure: true
